name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: graphics lib
      run:
        apt install libsdl2-dev
        apt install libsdl2-ttf-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
