name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: graphics-lib
      run: |
        sudo apt install libsdl2-dev
        sudo apt install libsdl2-ttf-dev
    #- name: configure
    #  run: ./configure
    - name: make
      run: make

  test:
    runs-on: ubuntu-latest

    steps:
      - name: do-tests
        run: |
          sudo apt install libcppunit-dev
          make test
